### ISSUE TITLE
Jodis 的jedis包

### ISSUE THREAD

**Issue by lirs72379** [CodisLabs/jodis#11]
你好，Jodis里面的包用了jedis2.7.3版本的。。。这个版本的jedis的JedisPoolConfig没有了setMaxActive和setMaxWait等方法，这两个方法改成其他什么方法了么？不通过jodis去连接，直接通过jedis连接的话，配置要怎么弄呢？

**Comment by yangzhe1991** [comment]
http://www.zyiqibook.com/article225.html 搜到一篇文章，不知道有没有帮助？

**Comment by lirs72379** [comment]
你好，我在用Jodis的时候，报了下面这个错误。麻烦帮忙看下勒
java.lang.VerifyError: (class: com/wandoulabs/jodis/RoundRobinJedisPool, method: resetPools signature: ()V) Incompatible argument to function

**Comment by Apache9** [comment]
这个错误一般是你的classpath下面有好几个jodis的jar吧？你检查一下？
