### ISSUE TITLE
jodis实现proxy的HA，是否实现了zk的HA？

### ISSUE THREAD

**Issue by aforesee** [CodisLabs/jodis#14]
`JedisResourcePool jedisPool = RoundRobinJedisPool.create()
        .curatorClient("zkserver:2181", 30000).zkProxyDir("/zk/codis/db_xxx/proxy").build();`
使用上述方式连接zkserver(我是应用启动的时候才获取一次zk)，假如zkserver挂掉的话，之后proxy再挂掉一个，实际使用中之前获取的jedisPool仍旧有挂掉的proxy
后来使用zkserver1:2181,zkserver2:2181,zkserver3:2181 这种模式再试，当其中的一个zk挂掉，其它的是可以正常使用的，zk的可用性方面是否使用zkserver1:2181,zkserver2:2181,zkserver3:2181这种方式？

**Comment by Apache9** [comment]
用你后面使用的那种方式是对的。一般来说你的zookeeper集群的机器最好全写进去。
