### ISSUE TITLE
jodis dubbo

### ISSUE THREAD

**Issue by chinaer** [CodisLabs/jodis#20]
我封装了jodis的dubbo服务，然后我们做压力测试的时候（500并发），之前还挺高的，能达到2wtps,但是后来我打算在出现异常的情况下打log日志，因此按理说不报错不会有日志记录，但是这样tps下降了1w,程序也没有报错，（我把dubbo的threads设置为了800，jodis的maxTotal设置为了1000，zkSessionTimeout设置为了30000），最后dump线程发现很多waiting状态，不知这是什么原因导致的？

**Comment by chinaer** [comment]
请问，如果我想把jodis封装成一个dubbo服务集中调用，这样并发大的情况下，如何有效的保证jodis连接够用的同时及时将资源还回对象池中，我看jedis底层用的comm-pool2,用官方推荐的Jedis jedis = jedisPool.getResource(); 每次dubbo调用就给一个连接，还是伴随每个操作的过程获取连接，使用后释放更好？@spinlock

**Comment by Apache9** [comment]
每次调用拿一个jedis对象出来用完close就好了，他会把连接还到连接池里
