### ISSUE TITLE
默认retry多次，tomcat启动超时

### ISSUE THREAD

**Issue by Tom-Goong** [CodisLabs/jodis#25]
设置retry重试策略后，“new RetryNTimes(0, 1000)“。。仍然重试连接zookeep了三次，导致应用不能在较短时间内启动。【除了延长启动时间，希望有其他方式处理】。thx

**Comment by spinlock** [comment]
zk 的连接策略之后会彻底修改掉。很快～

2016年8月15日星期一，Tom-Goong <notifications@github.com> 写道：

**Comment by yangzhe1991** [comment]
把代码改成异步初始化就好了吧

**Comment by Tom-Goong** [comment]
@spinlock @yangzhe1991 多谢，就用异步实例化代码吧

**Comment by spinlock** [comment]
sorry 是 jodis 啊，我以为 codis 了，这俩名字太像了。请忽略我。还纳闷为啥会有 tomcat 的问题。
