### ISSUE TITLE
codis-ha进程无端消失

### ISSUE THREAD

**Issue by ningning88x88** [CodisLabs/jodis#37]
看官网上写的在以下情况，codis-ha会退出，

从 codis-dashboard 获取集群状态失败时；
向 codis-dashboard 发送主从切换指令失败时；

问题（1）如果一个proxy和一个master死掉，那么无法主从切换成功，codis-ha会退出？
问题（2）能否针对上面的2种退出场景给一些案例

谢谢

**Comment by ningning88x88** [comment]
问题（3）2017/04/13 15:16:16 main.go:271: [WARN] try to promote group-[1], but synced = 0 & picked = 0, giveup
这种算第二个场景吗？

**Comment by Apache9** [comment]
这个是codis的问题，在codis那边开issue吧
