### ISSUE TITLE
一个连接用完即自动关闭，会不会引起频繁创建新连接？

### ISSUE THREAD

**Issue by JarvisZhu** [CodisLabs/jodis#40]
try (Jedis jedis = jedisPool.getResource()) {}
这种写法，一个连接用完之后即关闭，没有像JedisPool那样用完return回pool里吗？这样的话岂不是会频繁创建新连接？

**Comment by Apache9** [comment]
从某个版本开始的jedis，如果一个连接是从pool里拿出来的，close的时候会自动还回pool里，不是关闭连接。jodis依赖的jedis应该都是这样实现的。
