### ISSUE TITLE
问个连接池的问题

### ISSUE THREAD

**Issue by weilinqwe** [CodisLabs/jodis#41]
Jodis可以配连接池，我理解是Jodis到proxy的连接保持，那proxy到server之间有连接池吗（没看过proxy源码）？如果有，是不是jodis到proxy保持10个连接，那么proxy到各个server都有10个连接？如果空闲一个连接release掉，是不是proxy到各个server节点的连接都同步释放掉一个？

**Comment by Apache9** [comment]
proxy到后面redis server的连接池和你前面到proxy的连接没有关系，你想啊你同一个连接上来的请求可能会发到不同的redis server去的，这才是proxy的意义，这肯定不会有一对一的关系。
