### ISSUE TITLE
jodis 连接池是直接发送 RST 的？

### ISSUE THREAD

**Issue by ms2008** [CodisLabs/jodis#42]
我抓包分析到好像不是通过正常的 FIN 握手来完成？直接 RST，这么粗暴?

![rst](https://user-images.githubusercontent.com/3797918/27951257-de996202-6336-11e7-97f2-507f4bd6796f.png)

**Comment by Apache9** [comment]
啥意思？你是说关连接的时候吗？
jodis就是直接用的jedis的连接池，不是自己实现的。

**Comment by ms2008** [comment]
是的，proxy 日志看到发了 quit，但是却观察不到 TIME_WAIT，抓包显示全是 RST

**Comment by takeseem** [comment]
你意思是codis上的close问题？
