### ISSUE TITLE
希望jodis引用guava版本升级到最新21.0

### ISSUE THREAD

**Issue by jtf-joson** [CodisLabs/jodis#50]
使用项目springcloud项目，用到了jodis，发现都引用了guava，jodis引用的19.0版的，spring是21.0版的，导致项目报错，希望可以优化下

**Comment by jtf-joson** [comment]
![image](https://user-images.githubusercontent.com/13029953/38799786-0797c01e-4198-11e8-8aa5-c8caa3d02a84.png)
guava21.0 去掉了该方法，导致jodis引用报错了

**Comment by jtf-joson** [comment]
![image](https://user-images.githubusercontent.com/13029953/38800228-51675b4a-4199-11e8-8c42-ece4ae2aec21.png)
guava21.0去掉了该方法，导致jodis引用报错了

**Comment by Apache9** [comment]
看起来是curator的问题，我想想怎么搞比较好

**Comment by Apache9** [comment]
发了0.5.0，把curator升上去了，guava改成了23.0。你试试吧

**Comment by jtf-joson** [comment]
已经升级了，感谢
