### ISSUE TITLE
可以支持连接多个zookeeper吗？

### ISSUE THREAD

**Issue by andrewyoung51** [CodisLabs/jodis#51]
可以支持连接多个zookeeper吗？我看源码好像没有实现
如果配置codis集群，可能需要配置多个zookeeper。

**Comment by Apache9** [comment]
具体需求是啥？一个codis集群应该只会在一个zk上注册吧，如果你要连多个codis集群那直接创建多个pool，传不同的zk地址进去就行？

**Comment by Apache9** [comment]
zookeeper应该是一个外部系统，就是你得至少找三台机器，搭一个zookeeper集群，然后codis相关的组件都用这一个zookeeper

**Comment by andrewyoung51** [comment]
我们想要有一个主备，例如
RoundRobinJedisPool.create().curatorClient(url, (int) sessionTimeout).zkProxyDir(productName).build();
这个URL可以是192.168.1.2:2181,192.168.1.3:2181
而这两个zookeeper实际是同一个集群；
前一个连接失败，可以自动切换尝试连接第二个zookeeper。

**Comment by Apache9** [comment]
codis会注册在两个zk上嘛？

**Comment by andrewyoung51** [comment]
从proxy.toml来看，没有注册到两个zk
# Set jodis address & session timeout
#   1. jodis_name is short for jodis_coordinator_name, only accept "zookeeper" & "etcd".
#   2. jodis_addr is short for jodis_coordinator_addr
#   3. jodis_auth is short for jodis_coordinator_auth, for zookeeper/etcd, "user:password" is accepted.
#   4. proxy will be registered as node:
#        if jodis_compatible = true (not suggested):
#          /zk/codis/db_{PRODUCT_NAME}/proxy-{HASHID} (compatible with Codis2.0)
#        or else
#          /jodis/{PRODUCT_NAME}/proxy-{HASHID}
jodis_name = "zookeeper"
jodis_addr = "192.168.1.2:2181"
jodis_auth = ""
jodis_timeout = "20s"
jodis_compatible = false

**Comment by andrewyoung51** [comment]
`# Set jodis address & session timeout
#   1. jodis_name is short for jodis_coordinator_name, only accept "zookeeper" & "etcd".
#   2. jodis_addr is short for jodis_coordinator_addr
#   3. jodis_auth is short for jodis_coordinator_auth, for zookeeper/etcd, "user:password" is accepted.
#   4. proxy will be registered as node:
#        if jodis_compatible = true (not suggested):
#          /zk/codis/db_{PRODUCT_NAME}/proxy-{HASHID} (compatible with Codis2.0)
#        or else
#          /jodis/{PRODUCT_NAME}/proxy-{HASHID}
jodis_name = "zookeeper"
jodis_addr = "10.90.23.74:2181"
jodis_auth = ""
jodis_timeout = "20s"
jodis_compatible = false
`
