### ISSUE TITLE
0.3.0的jodis对应的后端是codis3集群，zk挂掉jodis是否能正常访问

### ISSUE THREAD

**Issue by zhangkaixuan** [CodisLabs/jodis#53]
如题，现在准备将线上codis2升级到codis3，但是业务端的jodis客户端（0.3.0）不能立即全部升级，启动了兼容codis2注册目录的proxy，此时若zk挂了，按照codis3的官方介绍不影响proxy，只是无法动态更新列表，请问若是jodis2的话是不是就会挂掉？

**Comment by Apache9** [comment]
zk挂了jodis应该也只是不能更新proxy列表了，如果你的proxy没有变化应该没有影响。
