### ISSUE TITLE
是否支持IPV6

### ISSUE THREAD

**Issue by DoraemonXX** [CodisLabs/jodis#54]
如果zk的环境是ipv6的，那么现在jodis的连接方式是否支持这种ipv6？还是需要如何改造客户端的连接代码？多谢

**Comment by Apache9** [comment]
我没有测试过IPV6的环境，不过jodis本身没有对ip做过什么限定，所以应该就是看curator和jedis是不是支持IPV6。

**Comment by DoraemonXX** [comment]
好的，多谢回复
