### ISSUE TITLE
jedis连接池不断重连导致proxy session数不断增长

### ISSUE THREAD

**Issue by weilinqwe** [CodisLabs/jodis#56]
我是spring-data-redis集成了jodis，然后发现连接池里的连接不停重连导致proxy session数不断增长。
一开始以为proxy的session_keepalive_period引起，但调试发现把它调大（比如7200s）也不能阻止断开重连，默认75s（在连接池调优情况下也不会引起断开重连）。
分析下来是由JedisPoolConfig配置引起，minEvictableIdleTimeMillis默认60s，改大（比如1800s）就可以，长时间内Idle连接很少。JedisPoolConfig默认策略是连接idle时间超过这个值并且idle连接数大于MaxIdle就会断开，但实际上好像只看连接idle时间超过这个值就断开了，然后idle连接数小于MinIdle就重连了，导致不停重连。
不知道大家有没有碰到过这个情况？

**Comment by yehaha9876** [comment]
现象一样。。。

**Comment by weilinqwe** [comment]
一个办法供参考：jedis pool里 setMinEvictableIdleTimeMillis 设置成一个较长的时间，比如半小时。还是有重连，但是少多了

**Comment by Apache9** [comment]
这个应该是jedis配置的问题？jodis只是包了一下jedis。
